branches:
  only:
    - master_local

environment:
  MINICONDA: "C:\\Miniconda"
  PYTHON: "C:\\Python36"
  PYTHON_VERSION: 3.6
  PYTHON_ARCH: 32

platform: x86

configuration: Release

init:
  - set PYTHONPATH=%PYTHON%
  - set PYTHONHOME=%PYTHON%
  - set PATH=%PYTHON%\Scripts;%PYTHON%;C:\Program Files (x86)\NSIS;%PATH%
  - python --version
  - python -m pip install -U pip setuptools wheel
  - pip install -U pypiwin32==223
  - pip install twisted[tls] certifi
  - pip install zope.interface
  - type nul > %PYTHON%\lib\site-packages\zope\__init__.py
  - curl -L https://bintray.com/alby128/py2exe/download_file?file_path=py2exe-0.9.3.2-cp36-none-win32.whl -o py2exe-0.9.3.2-cp36-none-win32.whl
  - pip install py2exe-0.9.3.2-cp36-none-win32.whl
  - del py2exe-0.9.3.2-cp36-none-win32.whl
  - pip install shiboken2==5.12.3 PySide2==5.12.3
  - pip freeze
  
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - for /F "tokens=2 delims='" %%a in ('findstr version syncplay\__init__.py') do @set ver=%%a
  - python buildPy2exe.py
  - type nul > syncplay_v%ver%\syncplay.ini

# Not a project with an msbuild file, build done at install.
build: off

artifacts:
  - path: 'syncplay_v$(ver)'
    type: zip
    name: Syncplay_$(ver)_Portable

  - path: Syncplay-$(ver)-Setup.exe
    name: Syncplay-$(ver)-Setup

# Push artefact to S3 bucket and list all
before_deploy:
  - dir
  #- python -c "from PySide2 import QtCore; print QtCore.QLibraryInfo.location(QtCore.QLibraryInfo.PluginsPath)"


# Deploy build to BinTray
deploy:
  provider: BinTray
  username: alby128
  api_key:
    secure: lAocj5KA9Z9x4BefQBIgNlQJbeW4qPBfCgYVBHMyOP3NgyhnMLmvR57ZCqtCKBlQ
  subject: alby128
  repo: Syncplay
  package: Syncplay
  version: v$(ver)
  publish: true
  override: true
    