language: objective-c
osx_image: xcode8.3

branches:
  only:
  - TLS

script:
- python3 buildPy2app.py py2app

before_install:
- brew update
#- cd $(brew --repo homebrew/core)
#- git fetch --depth=20000
#- git checkout 80860911cd26d9df62f3cc30575ed2076019ed1a
#- cd $TRAVIS_BUILD_DIR
- brew upgrade python
- which python3
- python3 --version
- which pip3
- pip3 --version
- brew install pyside
#- ln -s /usr/local/lib/python3.7/site-packages/PySide2/libpyside2.cpython-37m-darwin.5.11.dylib /usr/local/lib/
#- ln -s /usr/local/lib/python3.7/site-packages/PySide2/libshiboken2.cpython-37m-darwin.5.11.dylib /usr/local/lib/
- python3 -c "from PySide2 import __version__; print(__version__)"
- python3 -c "from PySide2.QtCore import __version__; print(__version__)" 
- pip3 install py2app
- python3 -c "from py2app.recipes import pyside2" 

install:
- pip3 install twisted appnope requests 
- pip3 install pyopenssl cffi

before_deploy:
- pip3 install dmgbuild
- mkdir dist_dmg
- mv resources/macos_vlc_install.command resources/.macos_vlc_install.command
- mv resources/lua/intf/syncplay.lua resources/lua/intf/.syncplay.lua
- mv resources/macOS_readme.pdf resources/.macOS_readme.pdf
- export VER="$(cat syncplay/__init__.py | awk '/version/ {gsub("\047", "", $3); print $NF}')"
- dmgbuild -s appdmg.py "Syncplay" dist_dmg/Syncplay_${VER}_TLS.dmg
- python3 bintray_version.py

deploy:
  skip_cleanup: true
  on: TLS
  provider: bintray
  file: "bintray.json"
  user: alby128
  key:
    secure: "N4XK9IxGEj+5aMskTEvUWwXSMXtHDFcjiLvnPRzVT3OOTSAA2AYjlH975MGiGEanap5gq5ftIo+M2TVNfiqflE9GSlFir+KfzabheoONZVegAq2sG6rDq9YElGJ8JefEb2O8vZykeyvow6TBxcsFdbV44RbGmf4obLALXKgK1cXG8MCKj8VOxVZpgaXFnNCxVlN1AlORx6MQ4ukaZMuO7fDnHjAgnkGlZOBq7/kMJfYGdZvLkKoe6qEoZHJQxVTcA3pkIwRQci5kx/AAxCuKcXYLpoHot5dytIumk0iwfzDqN4uUX5qOG8o2FrWy+7z/Yt7W97lA5c6hVltsoX5dqp0WB14EKgYq+wQwSNcI6tInjogDo4JnGSu1Tpmsy+Fc3Y5Z1cD29hWimxcC8h/wlm9C2hOjfEsdLOfkghevMjRdAW2RIIA8/KmR1Xi2EX78Q75wrPHvo4/4x0Cw0ZviN2wC9LY3GU8tmGjjC0P+WsF4M1Y9by2H2xLHuYPB7h7OnlD67d8pPQVq84Yl2jq9kT2PoYjlNwqWz1r/PsLBCGlXQtlTc7FQKXUAREFwBJY+b5mk2xMsiZZsNrtIfRQ2roDbHws+M0mAQPo1eqeDKLPH8fkDf/ZhWzE+swLadoGxuwKSux53ySAp7CQeObJYWJ3eHfO0cI21DZmd9uyjayA="