language: objective-c
osx_image: xcode6.4

branches:
  only:
  - qtpy-pyqt5

script:
- python buildPy2app.py py2app

before_install:
- brew install python
- curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/fdfc724dd532345f5c6cdf47dc43e99654e6a5fd/Formula/qt5.rb
- brew install ./qt5.rb
- which python
- which pip
- wget http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.6/PyQt5_gpl-5.6.tar.gz
- wget http://freefr.dl.sourceforge.net/project/pyqt/sip/sip-4.18/sip-4.18.tar.gz
- tar -xvf sip-4.18.tar.gz
- cd sip-4.18
- python configure.py -d /usr/local/lib/python2.7/site-packages/
- make
- make install
- cd ..
- tar -xvf PyQt5_gpl-5.6.tar.gz
- cd PyQt5_gpl-5.6
- python configure.py -d /usr/local/lib/python2.7/site-packages/ --qmake=/usr/local/Cellar/qt5/5.6.1-1/bin/qmake --sip=/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/sip --sip-incdir=../sip-4.18/siplib --confirm-license
- make
- make install
- rm -rf /usr/local/lib/python2.7/site-packages/PyQt5/uic/port_v3
- python -c "from PyQt5 import QtCore"
- pip install twisted appnope py2app

install:
- export QT_PREFERRED_BINDING="PyQt5"
- git clone -b qtpy-pyqt5 https://github.com/alby128/syncplay.git syncplay-qtpy-pyqt5
- cd syncplay-qtpy-pyqt5
- git checkout qtpy-pyqt5

before_deploy:
- pip install dmgbuild
- mkdir dist_dmg
- mv resources/macos_vlc_install.command resources/.macos_vlc_install.command
- dmgbuild -s appdmg.py "Syncplay" dist_dmg/Syncplay-qtpy-pyqt5.dmg

deploy:
  provider: s3
  access_key_id: AKIAJS554GLAZJ5L6TUA
  secret_access_key:
    secure: "iDuHZ6lgASU1O/9UKncgKfJZ96PpLzdKKvASDKCDPWBXXI5LyjGIIZJxbdjcE+WVoHYCCrN9Xn2XvhEjapqBzD2uKMH4QvN5mOG62FaPPOIPr+CCZxuEQuUQ8LUSIwQO3huu0K4eLn6q5b/ihmiWkTAssZFx1pccv15CJiwVPDwunULC2P55d/GxRohN2HcHDHGbHwlXasgvOx68xxbDEO4Ox7KRwcSIHnmx6vInQtzpqdnme8t1kmGG2vp6juyh39vCN0RzoJ5aH17qht/0nNvkbxnPcUg7jsDayOuWiwMgp4s+EYdyCh33IM3LQugxPqa3za5yjYQqC92SoaQg8FnsoU1sf7FHMCmb4mv8ZwgTD78+Ood/7lKHaOVGnxkoBtdrtXXf2tU/WyAGXTw4zc6eA+MIXC6FmNQFJaRUvGZPF+u+awHNJGAlmIhFOASBW4Ua6qahNzcasRE8e3cuzYuVzK4R24TRWqjYCadHd6SNh2FKVGYEKK1FcADUxn5GzldcovG3wsHRK6ONCS57s5xBlajVfEB4b78EqYkRgQQTAnCvNcUAbfsJOYywtSj/4keaGQeRydoY9qMl6MPpVXqn+r9bbglLBIOPzUr2EWXj/O6gq7bd9eSwCa1PvGplboDahkfWmVZKJ6rZpuvUfoQcKmuJiIpgowCczP9NNco="
  bucket: syncplay
  skip_cleanup: true
  region: eu-central-1
  local_dir: dist_dmg
  on:
    branch: qtpy-pyqt5
