"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from glob import glob
import syncplay

APP = ['syncplayClient.py']
DATA_FILES = [
    ('resources', glob('resources/*.png') + glob('resources/*.rtf')),
]
OPTIONS = {
	'iconfile': 'resources/icon.icns',
	'includes': {'PyQt5.QtCore', 'PyQt5.QtUiTools', 'PyQt5.QtGui','PyQt5.QtWidgets'},
    'qt_plugins': ['platforms/libqcocoa.dylib'],
	'plist': {
		'CFBundleName':'Syncplay',
		'CFBundleShortVersionString':syncplay.version,
		'CFBundleIdentifier':'pl.syncplay.Syncplay',
		'NSHumanReadableCopyright': '@ 2017 Syncplay All Rights Reserved'
	}
}

setup(
    app=APP,
    name='Syncplay',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
