"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from glob import glob
import syncplay

APP = ['syncplayClient.py']
DATA_FILES = [
    ('resources', glob('resources/*.png') + glob('resources/*.rtf')),
]
OPTIONS = {
	'iconfile': 'resources/icon.icns',
	'includes': {'PyQt5.QtCore', 'PyQt5.QtUiTools', 'PyQt5.QtGui','PyQt5.QtWidgets'},
	'excludes': {'PyQt5.QtHelp', 'PyQt5.QtMultimedia', 'PyQt5.QtMultimediaWidgets','PyQt5.QtNetwork', 'PyQt5.QtNfc', 'PyQt5.QtOpenGL', 'PyQt5.QtPrintSupport', 'PyQt5.QtSensors', 'PyQt5.QtSerialPort', 'PyQt5.QtQml', 'PyQt5.QtQuick', 'PyQt5.QtSql', 'PyQt5.QtSvg', 'PyQt5.QtTest', 'PyQt5.QtWebEngine', 'PyQt5.QtWebEngineCore',  'PyQt5.QtWebKit', 'PyQt5.QtWebKitWidgets', 'PyQt5.QtXml', 'PyQt5.QtXmlPatterns', 'PyQt5.QtDesigner', 'PyQt5.QtWebSockets', 'numpy', 'scipy'},
    'qt_plugins': ['platforms/libqcocoa.dylib'],
	'plist': {
		'CFBundleName':'Syncplay',
		'CFBundleShortVersionString':syncplay.version,
		'CFBundleIdentifier':'pl.syncplay.Syncplay',
		'NSHumanReadableCopyright': '@ 2017 Syncplay All Rights Reserved'
	}
}

setup(
    app=APP,
    name='Syncplay',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
