name: syncplay
summary: Syncplay
adopt-info: syncplay
summary: Client/server to synchronize media playback on many computers
description: |
  Syncplay synchronises the position and play state of multiple media players
  so that the viewers can watch the same thing at the same time. This means that
  when one person pauses/unpauses playback or seeks (jumps position) within their
  media player then this will be replicated across all media players connected to
  the same server and in the same 'room' (viewing session). When a new person
  joins they will also be synchronised. Syncplay also includes text-based chat so
  you can discuss a video as you watch it (or you could use third-party Voice over
  IP software to talk over a video).

confinement: classic
icon: syncplay/resources/syncplay.png
grade: stable
base: core20

apps:
  syncplay:
    command: bin/python3 $SNAP/bin/syncplay
    desktop: lib/python3.8/site-packages/syncplay/resources/syncplay.desktop
    environment:
      PYTHONPATH: $SNAP/lib/python3.8/site-packages/
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri

  syncplay-server:
    command: bin/syncplay-server
    environment:
      PYTHONPATH: $SNAP/lib/python3.8/site-packages/
    desktop: lib/python3.8/site-packages/syncplay/resources/syncplay-server.desktop

parts:
  syncplay:
    plugin: python
    source: .
    build-packages:
      - python3-dev
      - python3-wheel
    stage-packages:
      - libnss3
      - libxcomposite1
      - libxcursor1
      - libxtst6
      - libxrandr2
      - libglu1-mesa
      - libgles2-mesa
      - fontconfig
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libxi6
      - libegl1
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      - locales-all
      - libxslt1.1
      - xfonts-base
      - xfonts-scalable
      - libpython3-stdlib
      - libpython3.8-stdlib
      - libpython3.8-minimal
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-venv
      - python3-minimal
      - python3-distutils
      - python3-pkg-resources
      - python3.8-minimal
    python-packages:
      - wheel
      - pyside2
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(cat syncplay/__init__.py | awk '/version/ {gsub("\047", "", $3); print $NF}')

layout:
  /etc/fonts:
    bind: $SNAP/pyside/etc/fonts
