name: Build
on: push

jobs:
  macos:
    name: Build for macOS
    runs-on: macos-10.15
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Check Python install
        run: |
          which python3
          python3 --version
          which pip3
          pip3 --version

      - name: Install Python dependencies
        run: |   
          pip3 install twisted[tls] appnope requests certifi
          pip3 install shiboken2==5.13.1 pyside2==5.13.1
          pip3 install py2app
          python3 travis/pyside2_linker.py

      - name: Check Python dependencies
        run: |
          python3 -c "from PySide2 import __version__; print(__version__)"
          python3 -c "from PySide2.QtCore import __version__; print(__version__)" 
          python3 -c "from PySide2.QtCore import QLibraryInfo; print(QLibraryInfo.location(QLibraryInfo.LibrariesPath))"
          python3 -c "import ssl; print(ssl)"
          python3 -c "from py2app.recipes import pyside2"


      - name: Build
        run: |
          export DYLD_FRAMEWORK_PATH="$(python3 -c 'from PySide2.QtCore import QLibraryInfo; print(QLibraryInfo.location(QLibraryInfo.LibrariesPath))')" 
          python3 buildPy2app.py py2app

      - name: Prepare for deployment
        run: |
          ls -al
          export VER="$(cat syncplay/__init__.py | awk '/version/ {gsub("\047", "", $3); print $NF}')"
          echo "VER=$VER" >> $GITHUB_ENV
          mkdir dist_bintray
          travis/macos-deploy.sh
          ls -al dist_bintray

      - name: Deploy
        uses: actions/upload-artifact@v2
        with:
          name: Syncplay_${{ env.VER }}.dmg
          path: |
            dist_bintray/Syncplay_${{ env.VER }}.dmg
