name: Build
on: push

jobs:
  macos:
    name: Build for macOS
    runs-on: macos-10.15
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Install Homebrew dependencies
        run: |
          brew update > /dev/null
          which python3
          python3 --version
          which pip3
          pip3 --version
          brew install pyside qt

      - name: Check Homebrew dependencies
        run: |
          python3 -c "from PySide2 import __version__; print(__version__)"
          python3 -c "from PySide2.QtCore import __version__; print(__version__)" 
          python3 -c "import ssl; print(ssl)"

      - name: Install Python dependencies
        run: |   
          pip3 install py2app
          python3 -c "from py2app.recipes import pyside2"
          pip3 install twisted[tls] appnope requests certifi

      - name: Build
        run: python3 buildPy2app.py py2app

      - name: Prepare for deployment
        run: |
          ls -al
          export VER="$(cat syncplay/__init__.py | awk '/version/ {gsub("\047", "", $3); print $NF}')"
          python3 bintray_version.py
          mkdir dist_bintray
          travis/macos-deploy.sh

      - name: Deploy
        run: ls -al dist_bintray
        uses: bpicode/github-action-upload-bintray@master
        with:
          file: ./dist_bintray/Syncplay_${VER}.dmg
          api_user: alby128
          api_key: ${{ secrets.BINTRAY_API_KEY }}
          repository_user: syncplay
          repository: Syncplay
          package: Syncplay
          version: ${VER}
          publish: 1
          calculate_metadata: true
